const DATA_URL='data/news.json';
const SOURCES_URL='config/sources.json';
const AUTO_REFRESH_MS=5*60*1000;
const PAGE_SIZE=18;
const categories=['All','Frontier Models','Products & Agents','Research','Infrastructure','Open Source','Industry','Safety & Security','Compliance & Ethics'];

const state={items:[],sources:[],category:'All',source:'all',query:'',sort:'newest',savedOnly:false,visible:PAGE_SIZE,bookmarks:new Set(JSON.parse(localStorage.getItem('aiNewsBookmarks')||'[]')),nextRefresh:Date.now()+AUTO_REFRESH_MS};

const $=s=>document.querySelector(s);
const esc=s=>String(s??'').replace(/[&<>'"]/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#039;','"':'&quot;'}[m]));
const fmtDate=d=>{const x=new Date(d);if(Number.isNaN(x.getTime()))return 'Undated';const diff=Date.now()-x.getTime();const h=Math.floor(diff/36e5);if(h<1)return 'Just now';if(h<24)return `${h}h ago`;const days=Math.floor(h/24);if(days<7)return `${days}d ago`;return new Intl.DateTimeFormat('en',{day:'2-digit',month:'short',year:'numeric'}).format(x)};
const trustRank={official:0,primary:1,research:2,journalism:3,community:4};

function toast(message){const el=$('#toast');el.textContent=message;el.classList.add('show');clearTimeout(toast.t);toast.t=setTimeout(()=>el.classList.remove('show'),2400)}
function saveBookmarks(){localStorage.setItem('aiNewsBookmarks',JSON.stringify([...state.bookmarks]))}
function sourceFor(name){return state.sources.find(s=>s.name===name)||{} }

async function loadSources(){const r=await fetch(`${SOURCES_URL}?v=${Date.now()}`,{cache:'no-store'});if(!r.ok)throw new Error('Sources unavailable');const data=await r.json();state.sources=data.sources||[];renderSourceControls();renderSourceMatrix()}
async function loadNews({manual=false}={}){const btn=$('#refreshBtn');btn.classList.add('loading');try{const r=await fetch(`${DATA_URL}?v=${Date.now()}`,{cache:'no-store'});if(!r.ok)throw new Error('News dataset unavailable');const data=await r.json();state.items=Array.isArray(data.items)?data.items:[];state.generatedAt=data.generatedAt||null;state.visible=PAGE_SIZE;state.nextRefresh=Date.now()+AUTO_REFRESH_MS;renderAll();if(manual)toast(`Updated · ${state.items.length} AI stories`)}catch(err){console.error(err);toast('Could not refresh — showing last loaded data')}finally{btn.classList.remove('loading')}}

function renderAll(){renderMetrics();renderTicker();renderFeatured();renderNews();const d=state.generatedAt?new Date(state.generatedAt):null;$('#syncLabel').textContent=d&&!Number.isNaN(d)?`Dataset ${fmtDate(d)}`:'Dataset ready'}
function renderMetrics(){const compliance=state.items.filter(i=>i.category==='Compliance & Ethics').length;const primary=state.sources.filter(s=>['primary','official'].includes(s.class)).length;$('#metricStories').textContent=state.items.length.toLocaleString();$('#metricSources').textContent=state.sources.length.toLocaleString();$('#metricCompliance').textContent=compliance.toLocaleString();$('#metricPrimary').textContent=primary.toLocaleString();$('#sourceCountLabel').textContent=`${state.sources.length} CURATED SOURCES`}
function renderTicker(){const items=state.items.slice(0,12);const html=items.map(i=>`<a href="${esc(i.url)}" target="_blank" rel="noopener noreferrer"><strong>${esc(i.source)}</strong> · ${esc(i.title)}</a>`).join('');$('#ticker').innerHTML=html+html}
function renderFeatured(){const pool=filteredItems(false);const i=pool[0]||state.items[0];const el=$('#featured');if(!i){el.innerHTML='<div class="empty-state">No current item.</div>';return}const src=sourceFor(i.source);el.innerHTML=`<div class="feature-top"><span class="feature-source">${esc(i.source)}</span><span class="feature-index">TOP SIGNAL / ${esc(i.category)}</span></div><h2>${esc(i.title)}</h2><p>${esc(i.summary||'Open the original source for full context.')}</p><div class="feature-meta"><span>${esc(fmtDate(i.publishedAt))}</span><span>${esc(src.class||i.provenance||'source')}</span>${i.tags?.slice(0,2).map(t=>`<span>${esc(t)}</span>`).join('')||''}<a href="${esc(i.url)}" target="_blank" rel="noopener noreferrer">Open original ↗</a></div>`}

function filteredItems(limit=true){let arr=[...state.items];if(state.category!=='All')arr=arr.filter(i=>i.category===state.category);if(state.source!=='all')arr=arr.filter(i=>i.source===state.source);if(state.savedOnly)arr=arr.filter(i=>state.bookmarks.has(i.id));if(state.query){const q=state.query.toLowerCase();arr=arr.filter(i=>`${i.title} ${i.summary} ${i.source} ${(i.tags||[]).join(' ')}`.toLowerCase().includes(q))}if(state.sort==='source')arr.sort((a,b)=>a.source.localeCompare(b.source)||new Date(b.publishedAt)-new Date(a.publishedAt));else if(state.sort==='trust')arr.sort((a,b)=>(trustRank[sourceFor(a.source).class]??9)-(trustRank[sourceFor(b.source).class]??9)||new Date(b.publishedAt)-new Date(a.publishedAt));else arr.sort((a,b)=>new Date(b.publishedAt)-new Date(a.publishedAt));return limit?arr.slice(0,state.visible):arr}
function renderNews(){const all=filteredItems(false),items=all.slice(0,state.visible),grid=$('#newsGrid'),tpl=$('#newsCardTemplate');grid.innerHTML='';if(!items.length){grid.innerHTML='<div class="empty-state"><strong>No matching AI stories.</strong><br>Try another category, source or search term.</div>'}else items.forEach(item=>{const node=tpl.content.cloneNode(true),card=node.querySelector('.news-card'),src=sourceFor(item.source),save=node.querySelector('.save-btn');node.querySelector('.source-badge').textContent=item.source;node.querySelector('.category').textContent=item.category;node.querySelector('time').textContent=fmtDate(item.publishedAt);node.querySelector('h3').textContent=item.title;node.querySelector('.summary').textContent=item.summary||'Open the original source for the complete article.';node.querySelector('.provenance').textContent=(src.class||item.provenance||'source').replaceAll('_',' ');const link=node.querySelector('.card-bottom a');link.href=item.url;save.textContent=state.bookmarks.has(item.id)?'★':'☆';save.classList.toggle('saved',state.bookmarks.has(item.id));save.addEventListener('click',()=>{if(state.bookmarks.has(item.id)){state.bookmarks.delete(item.id);toast('Removed from saved stories')}else{state.bookmarks.add(item.id);toast('Saved locally')}saveBookmarks();renderNews()});card.dataset.category=item.category;grid.appendChild(node)});$('#resultsLabel').textContent=`${all.length} MATCHING · SHOWING ${Math.min(items.length,all.length)}`;$('#loadMoreBtn').hidden=items.length>=all.length}

function renderSourceControls(){const chips=$('#categoryChips');chips.innerHTML=categories.map(c=>`<button type="button" class="chip ${c==='All'?'active':''}" data-category="${esc(c)}">${esc(c)}</button>`).join('');chips.addEventListener('click',e=>{const b=e.target.closest('[data-category]');if(!b)return;state.category=b.dataset.category;state.visible=PAGE_SIZE;document.querySelectorAll('.chip').forEach(x=>x.classList.toggle('active',x===b));renderFeatured();renderNews()});const sel=$('#sourceSelect');const names=[...state.sources].sort((a,b)=>a.name.localeCompare(b.name));sel.innerHTML='<option value="all">All sources</option>'+names.map(s=>`<option value="${esc(s.name)}">${esc(s.name)}</option>`).join('')}
function renderSourceMatrix(){const groups=[['Primary Labs','primary'],['Research','research'],['Journalism','journalism'],['Governance & Standards','official','governance']];$('#sourceMatrix').innerHTML=groups.map(([label,...classes])=>{const list=state.sources.filter(s=>classes.includes(s.class));return `<div class="source-group"><h3>${esc(label)} · ${list.length}</h3>${list.map(s=>`<a href="${esc(s.homepage)}" target="_blank" rel="noopener noreferrer"><strong>${esc(s.name)}</strong><span>${s.feed?'LIVE FEED':'WATCH'}</span></a>`).join('')}</div>`}).join('')}

function applyExternalFilter(category){state.category=category;state.visible=PAGE_SIZE;document.querySelectorAll('.chip').forEach(x=>x.classList.toggle('active',x.dataset.category===category));renderFeatured();renderNews();$('#newsTitle').scrollIntoView({behavior:'smooth',block:'start'})}

$('#searchInput').addEventListener('input',e=>{state.query=e.target.value.trim();state.visible=PAGE_SIZE;renderFeatured();renderNews()});
$('#sourceSelect').addEventListener('change',e=>{state.source=e.target.value;state.visible=PAGE_SIZE;renderNews()});
$('#sortSelect').addEventListener('change',e=>{state.sort=e.target.value;renderNews()});
$('#bookmarksOnly').addEventListener('change',e=>{state.savedOnly=e.target.checked;state.visible=PAGE_SIZE;renderNews()});
$('#loadMoreBtn').addEventListener('click',()=>{state.visible+=PAGE_SIZE;renderNews()});
$('#refreshBtn').addEventListener('click',()=>loadNews({manual:true}));
document.querySelectorAll('[data-filter]').forEach(b=>b.addEventListener('click',()=>applyExternalFilter(b.dataset.filter)));
$('#themeBtn').addEventListener('click',()=>{document.documentElement.classList.toggle('light');localStorage.setItem('aiNewsTheme',document.documentElement.classList.contains('light')?'light':'dark')});
if(localStorage.getItem('aiNewsTheme')==='light')document.documentElement.classList.add('light');

setInterval(()=>{const remaining=Math.max(0,state.nextRefresh-Date.now()),m=Math.floor(remaining/60000),s=Math.floor((remaining%60000)/1000);$('#refreshCountdown').textContent=`${String(m).padStart(2,'0')}:${String(s).padStart(2,'0')}`;if(remaining<=1000)loadNews()},1000);

if('serviceWorker'in navigator)window.addEventListener('load',()=>navigator.serviceWorker.register('sw.js').catch(()=>{}));
Promise.allSettled([loadSources(),loadNews()]).then(()=>renderAll());
