(function(){
  "use strict";
  var FILTER_KEY="aiNewsWebFiltersV33";
  var SOURCE_KEY="aiNewsWebSourcesV33";
  var SOCIAL_KEY="aiNewsWebSocialV33";
  var extendedLoaded=false;
  var feedBusy=false;
  var feedStamp=0;
  function q(s){return document.querySelector(s)}
  function qq(s){return Array.prototype.slice.call(document.querySelectorAll(s))}
  function app(){return window.AINewsWebState||null}
  function esc(v){return String(v==null?"":v).replace(/[&<>"']/g,function(m){return({"&":"&amp;","<":"&lt;",">":"&gt;","\"":"&quot;","'":"&#39;"}[m])})}
  function read(key){try{var x=JSON.parse(localStorage.getItem(key)||"[]");return Array.isArray(x)?x:[]}catch(e){return[]}}
  function write(key,x){try{localStorage.setItem(key,JSON.stringify(x))}catch(e){}}
  function toastW(t){var el=q("#toast");if(!el)return;el.textContent=t;el.classList.add("show");setTimeout(function(){el.classList.remove("show")},2400)}
  function render(){try{window.AINewsWebRender()}catch(e){}setTimeout(renderV33,50)}
  function ext(url){if(!url||!/^(https?:)\/\//i.test(url))return;try{window.open(url,"_blank","noopener,noreferrer")}catch(e){}}
  function merge(base,extra,key){var out=[],seen=new Set();(base||[]).concat(extra||[]).forEach(function(x){if(!x||!x[key]||seen.has(x[key]))return;seen.add(x[key]);out.push(x)});return out}
  function applySocialDirectory(s,d){var list=(d&&d.providers)||[],by=new Map(list.map(function(x){return[x.id,x]})),changed=false;(s.providers||[]).forEach(function(p){var x=by.get(p.id);if(x&&x.social){var before=JSON.stringify(p.social||{});p.social=Object.assign({},x.social,p.social||{});if(JSON.stringify(p.social)!==before)changed=true}});return changed}
  function textNode(node,name){var a=node.getElementsByTagName(name);return a&&a[0]?String(a[0].textContent||"").trim():""}
  function linkNode(node){var a=node.getElementsByTagName("link"),i;for(i=0;i<a.length;i++){var h=a[i].getAttribute("href");if(h)return h}return a&&a[0]?String(a[0].textContent||"").trim():""}
  function slug(v){return String(v||"item").toLowerCase().replace(/[^a-z0-9]+/g,"-").slice(0,44)}
  function feedItems(source,xml){var doc=new DOMParser().parseFromString(xml,"text/xml");return Array.prototype.slice.call(doc.querySelectorAll("item,entry")).slice(0,24).map(function(n,i){var title=textNode(n,"title");if(!title)return null;var url=linkNode(n)||source.homepage||source.feed;var summary=textNode(n,"description")||textNode(n,"summary")||textNode(n,"content");var d=textNode(n,"pubDate")||textNode(n,"published")||textNode(n,"updated")||new Date().toISOString();var stamp;try{stamp=new Date(d).toISOString()}catch(e){stamp=new Date().toISOString()}return{id:"custom-web-v33:"+slug(source.name)+":"+i+":"+slug(title),title:title,summary:summary.replace(/<[^>]+>/g," ").replace(/\s+/g," ").trim().slice(0,420),url:url,source:source.name,publishedAt:stamp,category:(source.tags||[]).some(function(x){return /research|paper/i.test(x)})?"Research":"Industry",provenance:source.class||"community",aiConfidence:"medium",providers:[],tags:(source.tags||[]).slice(0,8),customSource:true}}).filter(Boolean)}
  async function fetchOne(source){try{var r=await fetch(source.feed+"?v="+Date.now(),{cache:"no-store"});return r.ok?feedItems(source,await r.text()):[]}catch(e){return[]}}
  function ensureSources(){var s=app();if(!s)return false;var changed=false,known=new Set((s.sources||[]).map(function(x){return x.name}));read(SOURCE_KEY).forEach(function(x){if(x&&x.name&&!known.has(x.name)){s.sources.push(x);known.add(x.name);changed=true}});return changed}
  async function loadExtended(){if(extendedLoaded||!app())return;extendedLoaded=true;try{var r=await Promise.all([fetch("config/providers-extra.json?v="+Date.now()).then(function(x){return x.json()}).catch(function(){return{providers:[]}}),fetch("config/sources-extra.json?v="+Date.now()).then(function(x){return x.json()}).catch(function(){return{sources:[]}}),fetch("config/social-directory.json?v="+Date.now()).then(function(x){return x.json()}).catch(function(){return{providers:[]}})]),s=app(),bp=s.providers.length,bs=s.sources.length;s.providers=merge(s.providers,r[0].providers||[],"id");s.sources=merge(s.sources,r[1].sources||[],"name");var socialChanged=applySocialDirectory(s,r[2]);ensureSources();if(bp!==s.providers.length||bs!==s.sources.length||socialChanged)render();fetchCustomFeeds(true)}catch(e){}}
  async function fetchCustomFeeds(force){var now=Date.now();if(feedBusy||(!force&&now-feedStamp<300000))return;var sources=read(SOURCE_KEY).filter(function(x){return x&&x.feed});if(!sources.length)return;feedBusy=true;feedStamp=now;try{var b=await Promise.all(sources.map(fetchOne)),incoming=[];b.forEach(function(x){incoming=incoming.concat(x)});var s=app();if(!s)return;s.items=(s.items||[]).filter(function(x){return String(x.id||"").indexOf("custom-web-v33:")!==0}).concat(incoming);s.items.sort(function(a,b){return new Date(b.publishedAt)-new Date(a.publishedAt)});render();toastW(incoming.length?"Added "+incoming.length+" custom feed signals":"Custom feeds checked")}finally{feedBusy=false}}
  function nav(){if(q("#v32WebNav"))return;var top=q(".topbar");if(!top)return;top.insertAdjacentHTML("afterend","<nav id=\"v32WebNav\" class=\"v32-web-nav\"><button data-v33-target=\"top\" class=\"active\">⌂ Command</button><button data-v33-target=\"stream\">⌕ Live feed</button><button data-v33-target=\"providers\">⬡ LLM Wire</button><button data-v33-target=\"governance\">◇ Governance</button><button data-v33-target=\"social\">◎ Official Social</button><button data-v33-open>⚙ My Workspace</button><span class=\"web-live\"><i></i><b id=\"v33Live\">LIVE</b></span></nav>")}
  function overview(){var hero=q(".hero");if(!hero||q("#v32WebOverview"))return;hero.insertAdjacentHTML("afterend","<section id=\"v32WebOverview\" class=\"v32-web-overview shell\"><div class=\"v32-web-overview-head\"><div><small>COMMAND CENTER · LIVE OVERVIEW</small><strong>See the whole intelligence layer at a glance</strong></div><span id=\"v33OverviewMeta\">source-first · local controls</span></div><div class=\"v32-web-overview-grid\"><article class=\"v32-web-card\" data-v33-target=\"stream\"><header><span>SIGNAL ATLAS</span><b id=\"v33AtlasCount\">—</b></header><h3>What is moving</h3><p>Category momentum, relevance and current newsroom activity across the AI-only feed.</p><div id=\"v33AtlasBars\" class=\"v32-web-bars\"></div><div class=\"v32-web-footer\"><span id=\"v33AtlasFoot\">Live feed</span><strong>EXPLORE ›</strong></div></article><article class=\"v32-web-card\" data-v33-target=\"providers\"><header><span>PROVIDER MATRIX</span><b id=\"v33ProviderCount\">—</b></header><h3>Who is shaping it</h3><p>Complete provider directory with first-party coverage, ecosystem activity and social links.</p><div id=\"v33ProviderBars\" class=\"v32-web-bars\"></div><div class=\"v32-web-footer\"><span id=\"v33ProviderFoot\">LLM Wire</span><strong>OPEN WIRE ›</strong></div></article></div></section>")}
  function filterBar(){var deck=q(".control-deck");if(!deck||q("#v33FilterToggle"))return;deck.insertAdjacentHTML("afterbegin","<button id=\"v33FilterToggle\" class=\"v32-web-filter-toggle\"><span>FILTER WORKSPACE · search stays visible</span><span id=\"v33FilterState\">OPEN · tap to minimize</span></button>");deck.insertAdjacentHTML("beforeend","<div class=\"v32-web-filter-tools\"><div><strong>Personal views</strong><span>Save reusable filters and source combinations locally.</span></div><button data-v33-open>Customize</button></div>");var compact=localStorage.getItem("v33FiltersCollapsed")==="1";deck.classList.toggle("v32-web-filters-collapsed",compact);updateFilterState()}
  function updateFilterState(){var deck=q(".control-deck"),label=q("#v33FilterState");if(!deck||!label)return;label.textContent=deck.classList.contains("v32-web-filters-collapsed")?"CLOSED · tap to expand":"OPEN · tap to minimize"}
  function modal(){if(q("#v32WebModal"))return;document.body.insertAdjacentHTML("beforeend","<aside id=\"v32WebModal\" aria-hidden=\"true\"><div class=\"v32-web-modal-panel\"><div class=\"v32-web-modal-head\"><div><small>PERSONAL INTELLIGENCE WORKSPACE</small><h2>Build your own news surface</h2></div><button data-v33-close>×</button></div><p>Use your own RSS/Atom feeds, saved query filters and official social links. Everything added here remains local to this browser and opens original sources.</p><section class=\"v32-web-module\"><h3>Saved filters</h3><small>Examples: provider:openai cat:Research · tag:Agents · is:primary</small><div class=\"v32-web-form\"><input id=\"v33FilterName\" placeholder=\"Filter name\"><input id=\"v33FilterQuery\" placeholder=\"provider:openai cat:Research\"><button data-v33-filter-save>Save</button></div><div id=\"v33FilterList\" class=\"v32-web-list\"></div></section><section class=\"v32-web-module\"><h3>Personal sources</h3><small>Add a homepage or a reachable RSS/Atom URL. Feed access depends on the publisher's CORS policy.</small><div class=\"v32-web-form source\"><input id=\"v33SourceName\" placeholder=\"Source name\"><input id=\"v33SourceHomepage\" placeholder=\"Official homepage\"><input id=\"v33SourceFeed\" placeholder=\"RSS / Atom URL (optional)\"><input id=\"v33SourceRegion\" placeholder=\"Region / language\"><select id=\"v33SourceClass\"><option value=\"community\">Community / independent</option><option value=\"journalism\">Journalism</option><option value=\"research\">Research</option><option value=\"primary\">Primary lab</option><option value=\"official\">Official institution</option></select><input id=\"v33SourceTags\" placeholder=\"Tags, comma separated\"><button data-v33-source-save>Save personal source</button></div><div class=\"v32-web-note\">Source-first rule: AI News stores only feed metadata needed for the local list; it does not copy article pages.</div></section><section class=\"v32-web-module\"><h3>Official social channels</h3><small>Keep a personal directory of official profiles; posts and media are opened on the original platform.</small><div class=\"v32-web-form source\"><input id=\"v33SocialLabel\" placeholder=\"Provider or organization\"><select id=\"v33SocialPlatform\"><option value=\"linkedin\">LinkedIn</option><option value=\"x\">X</option><option value=\"youtube\">YouTube</option><option value=\"instagram\">Instagram</option><option value=\"facebook\">Facebook</option><option value=\"mastodon\">Mastodon</option><option value=\"other\">Other official channel</option></select><input id=\"v33SocialUrl\" placeholder=\"https://…\"><button data-v33-social-save>Save official channel</button></div><div id=\"v33SocialList\" class=\"v32-web-social\"></div></section></div></aside>")}
  function renderOverview(){var s=app();if(!s)return;var items=s.items||[],cats={},ps={};items.forEach(function(i){cats[i.category||"AI"]=(cats[i.category||"AI"]||0)+1;(i.providers||[]).forEach(function(id){ps[id]=(ps[id]||0)+1})});var ck=Object.keys(cats).sort(function(a,b){return cats[b]-cats[a]}).slice(0,4),pk=Object.keys(ps).sort(function(a,b){return ps[b]-ps[a]}).slice(0,4),mc=cats[ck[0]]||1,mp=ps[pk[0]]||1,cb=q("#v33AtlasBars"),pb=q("#v33ProviderBars");if(cb)cb.innerHTML=ck.map(function(k){return"<div class=\"v32-web-bar\"><span>"+esc(k)+"</span><i style=\"--w:"+Math.max(12,Math.round(cats[k]/mc*100))+"%\"></i><b>"+cats[k]+"</b></div>"}).join("")||"<span class=\"muted\">No data</span>";if(pb)pb.innerHTML=pk.map(function(id){var p=(s.providers||[]).find(function(x){return x.id===id})||{};return"<div class=\"v32-web-bar\"><span>"+esc(p.name||id)+"</span><i style=\"--w:"+Math.max(12,Math.round(ps[id]/mp*100))+"%\"></i><b>"+ps[id]+"</b></div>"}).join("")||"<span class=\"muted\">No data</span>";var ac=q("#v33AtlasCount"),pc=q("#v33ProviderCount"),af=q("#v33AtlasFoot"),pf=q("#v33ProviderFoot"),m=q("#v33OverviewMeta"),live=q("#v33Live");if(ac)ac.textContent=items.length+" stories";if(pc)pc.textContent=(s.providers||[]).length+" providers";if(af)af.textContent=ck.length+" desks active";if(pf)pf.textContent=(s.sources||[]).length+" sources";if(m)m.textContent=(s.sources||[]).length+" sources · "+(s.providers||[]).length+" providers";if(live)live.textContent=items.length+" LIVE"}
  function renderFilters(){var host=q("#v33FilterList");if(!host)return;var a=read(FILTER_KEY);host.innerHTML=a.length?a.map(function(x){return"<button class=\"v32-web-chip\" data-v33-filter-apply=\""+esc(x.id)+"\"><strong>"+esc(x.name)+"</strong><em data-v33-filter-delete=\""+esc(x.id)+"\">×</em></button>"}).join(""):"<span class=\"muted\">No saved filters yet.</span>"}
  function applyFilter(f){var s=app();if(!s)return;s.query=f.query;s.category="All";s.provider="all";s.source="all";s.visible=18;var input=q("#searchInput");if(input)input.value=f.query;render();q("#stream")?.scrollIntoView({behavior:"smooth",block:"center"});toastW("Filter applied · "+f.name)}
  function saveFilter(){var n=q("#v33FilterName")?.value.trim(),v=q("#v33FilterQuery")?.value.trim();if(!n||!v){toastW("Add a name and query first");return}var a=read(FILTER_KEY).filter(function(x){return x.name!==n});a.push({id:"f-"+Date.now(),name:n,query:v});write(FILTER_KEY,a);q("#v33FilterName").value="";q("#v33FilterQuery").value="";renderFilters();toastW("Saved filter · "+n)}
  function deleteFilter(id){write(FILTER_KEY,read(FILTER_KEY).filter(function(x){return x.id!==id}));renderFilters();toastW("Filter removed")}
  function saveSource(){var name=q("#v33SourceName")?.value.trim(),homepage=q("#v33SourceHomepage")?.value.trim(),feed=q("#v33SourceFeed")?.value.trim(),region=q("#v33SourceRegion")?.value.trim()||"Global",klass=q("#v33SourceClass")?.value||"community",tags=(q("#v33SourceTags")?.value||"").split(",").map(function(x){return x.trim()}).filter(Boolean);if(!name||(!homepage&&!feed)){toastW("Add a name and a homepage or feed URL");return}if(homepage&&!/^https?:\/\//i.test(homepage))homepage="https://"+homepage;if(feed&&!/^https?:\/\//i.test(feed))feed="https://"+feed;var source={name:name,homepage:homepage||feed,feed:feed||null,class:klass,region:region,tags:tags,strictAI:true,custom:true};var a=read(SOURCE_KEY).filter(function(x){return x.name!==name});a.push(source);write(SOURCE_KEY,a);ensureSources();render();fetchCustomFeeds(true);toastW("Personal source added · "+name)}
  function saveSocial(){var label=q("#v33SocialLabel")?.value.trim(),platform=q("#v33SocialPlatform")?.value||"other",url=q("#v33SocialUrl")?.value.trim();if(!label||!url){toastW("Add a label and official URL");return}if(!/^https?:\/\//i.test(url))url="https://"+url;var a=read(SOCIAL_KEY);a.push({id:"s-"+Date.now(),label:label,platform:platform,url:url});write(SOCIAL_KEY,a);q("#v33SocialLabel").value="";q("#v33SocialUrl").value="";renderSocial();toastW("Official channel saved")}
  function deleteSocial(id){write(SOCIAL_KEY,read(SOCIAL_KEY).filter(function(x){return x.id!==id}));renderSocial()}
  function renderSocial(){var host=q("#v33SocialList");if(host){var a=read(SOCIAL_KEY);host.innerHTML=a.length?a.map(function(x){return"<div class=\"v32-web-social-row\"><div><strong>"+esc(x.label)+" · "+esc(x.platform)+"</strong><small>"+esc(x.url)+"</small></div><button data-v33-social-delete=\""+esc(x.id)+"\">×</button></div>"}).join(""):"<span class=\"muted\">No personal channels yet.</span>"}var grid=q("#socialGrid");if(!grid)return;qq("#socialGrid .v32-web-source-card").forEach(function(x){x.remove()});read(SOCIAL_KEY).forEach(function(x){var a=document.createElement("a");a.className="social-card v32-web-source-card";a.href=x.url;a.target="_blank";a.rel="noopener noreferrer";a.innerHTML="<span class=\"social-icon\">↗</span><div><small>"+esc(x.platform.toUpperCase())+"</small><strong>"+esc(x.label)+"</strong><span>Open official profile ↗</span></div>";grid.appendChild(a)})}
  function syncNav(){var y=window.scrollY+150,best="top";["stream","providers","governance","social"].forEach(function(id){var el=q("#"+id);if(el&&el.offsetTop<=y)best=id});qq("#v32WebNav [data-v33-target]").forEach(function(b){b.classList.toggle("active",b.getAttribute("data-v33-target")===best)})}
  function events(){document.addEventListener("click",function(e){var t=e.target.closest("[data-v33-target]");if(t){e.preventDefault();q("#"+t.getAttribute("data-v33-target"))?.scrollIntoView({behavior:"smooth",block:"start"});return}if(e.target.closest("[data-v33-open]")){q("#v32WebModal").classList.add("open");q("#v32WebModal").setAttribute("aria-hidden","false");renderFilters();renderSocial();return}if(e.target.closest("[data-v33-close]")){q("#v32WebModal").classList.remove("open");q("#v32WebModal").setAttribute("aria-hidden","true");return}if(e.target.closest("#v33FilterToggle")){var deck=q(".control-deck");deck.classList.toggle("v32-web-filters-collapsed");localStorage.setItem("v33FiltersCollapsed",deck.classList.contains("v32-web-filters-collapsed")?"1":"0");updateFilterState();return}var a=e.target.closest("[data-v33-filter-apply]");if(a){var f=read(FILTER_KEY).find(function(x){return x.id===a.getAttribute("data-v33-filter-apply")});if(f)applyFilter(f);return}var d=e.target.closest("[data-v33-filter-delete]");if(d){e.preventDefault();e.stopPropagation();deleteFilter(d.getAttribute("data-v33-filter-delete"));return}if(e.target.closest("[data-v33-filter-save]")){e.preventDefault();e.stopPropagation();saveFilter();return}if(e.target.closest("[data-v33-source-save]")){e.preventDefault();e.stopPropagation();saveSource();return}if(e.target.closest("[data-v33-social-save]")){e.preventDefault();e.stopPropagation();saveSocial();return}var sd=e.target.closest("[data-v33-social-delete]");if(sd){deleteSocial(sd.getAttribute("data-v33-social-delete"));return}},true);window.addEventListener("scroll",syncNav,{passive:true});var refresh=q("#refreshBtn");if(refresh)refresh.addEventListener("click",function(){setTimeout(function(){ensureSources();fetchCustomFeeds(true);renderV33()},1000)})}
  function articleOpen(){document.addEventListener("click",function(e){var card=e.target.closest(".news-card,.featured");if(!card||e.target.closest("button,a,input,select,textarea"))return;var s=app(),id=card.getAttribute("data-story-id"),item=id&&s?s.items.find(function(x){return x.id===id}):null;if(!item){var title=card.querySelector("h2,h3")?.textContent||"";item=s&&s.items.find(function(x){return x.title===title})}if(item){e.preventDefault();e.stopPropagation();ext(item.url)}},true)}
  function renderV33(){var s=app();if(!s)return;ensureSources();renderOverview();renderFilters();renderSocial();var l=q("#sourceCountLabel");if(l)l.textContent=(s.sources||[]).length+" CURATED SOURCES"}
  function boot(n){if(!app()||!q("main")){if(n<60)setTimeout(function(){boot(n+1)},150);return}if(document.body.classList.contains("v32-web"))return;document.body.classList.add("v32-web");nav();overview();filterBar();modal();events();articleOpen();renderV33();loadExtended();setInterval(function(){if(ensureSources())render();renderV33()},3000)}
  if(document.readyState==="loading")document.addEventListener("DOMContentLoaded",function(){boot(0)});else boot(0)
})();